on:
  release:
    types: [created]

jobs:
  release:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Publish
        env:
          ORG_GRADLE_PROJECT_githubUsername: ${{ github.actor }}
          ORG_GRADLE_PROJECT_githubPassword: ${{ github.token }}
          NEXUS_USER: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PW: ${{ secrets.NEXUS_PASSWORD }}
          SIGNING_KEY: ${{ secrets.S_SIGNING_KEY }}
          SIGNING_PW: ${{ secrets.S_SIGNING_PASSWORD }}
        run: ./gradlew clean publishAllPublicationsToSonatypeRepository
